### ISSUE TITLE
Possible issues in Fit_GPcounts initialisation with set_X_Y(self,X,Y) 

### ISSUE THREAD

**Issue by lijing-lin** [ManchesterBioinference/GPcounts#4]
`__init__` in `Fit_GPcounts()` calls`set_X_Y(self,X,Y)` to initialise the object with input data `Y` using the following lines:
``` 
            if self.lik_name == 'Gaussian':
                self.Y = self.Y.values # gene expression matrix
            else:
                self.Y = self.Y.values.astype(int)
                self.Y = self.Y.astype(float)
```
However, when defining an  `Fit_GPcounts()` object, `lik_name` was not passed on as an input argument and `self.lik_name` is set to `None`. Therefore the code always goes to set `Y` to be integer even though one wants to fit with a Gaussian likelihood only.

**Comment by NuhaSaud** [comment]
Hi lijing-lin,

Thank you for using GPcounts,

We have moved set_X_Y(self,X,Y) under each test statistics so that self.lik_name will not set to None and truncate the decimal part done only if transform flag is set to False.  Otherwise, we truncate any decimal part to make sure gene expression matrix Y is counts.

Best wishes, 
Nuha.
