### ISSUE TITLE
One_sample_test Error

### ISSUE THREAD

**Issue by ngocphuongtran** [ManchesterBioinference/GPcounts#6]
I was trying to reproduce the gpcounts_spatial notebooks with Colorectal Cancer data. But calling the one_sample_test causes an error:

![](https://user-images.githubusercontent.com/76912457/107375022-946c1400-6ae8-11eb-935c-154c4caa7fc3.png)

I would very much appreciate clarification on the issue.

**Comment by sokratiag** [comment]
Hi,

Could you please post a screenshot with the whole script you used to run your case? Then I can try to find out what's the issue.

**Comment by ngocphuongtran** [comment]
Hi,

This is my code.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/76912457/107498388-02b9e080-6b94-11eb-8903-1f814c0b51a4.png">

<img width="925" alt="image" src="https://user-images.githubusercontent.com/76912457/107498424-0cdbdf00-6b94-11eb-8e5b-b5bb1bd1811d.png">

Thanks for your help!

**Comment by sokratiag** [comment]
Hi, thanks for posting this. I had a look and it seems that the error is coming from the definition of the 'scales'. The scales variable should have the same dimension as your gene expression counts matrix. So in your case it should be n_rows x n_columns **so that a scale factor for each gene at each location is required**.  In your case, you define 'scales' as the total _counts at each location so you end up with just one column. Please take a look at the example provided with the Mouse_OB data set and see how the scales are calculated using the R code. For example, if you do nb_scaled = False, then the code works OK. Please bear in mind that a visium data set would be computationally expensive (it will take really a long time to run) so you might need to use the sparse version of the GPcounts code. 

In this case, you need to give the number of inducing points, we could calculate an optimal number using import scipy as sp
sp.special.wrightomega(np.log(X.shape[0])) but i would suggest to use more than than (maybe try different numbers of inducing points and see how your results look like). 

Then you need to do:

gene_name = []
sparse = True 
nb_scaled = True # set the nb_scaled argument to True to pass the scale factors 
gene_name = Y_run.index
likelihood = 'Negative_binomial' 
gp_counts = Fit_GPcounts(X,Y_run.loc[gene_name], scale = scale, sparse = sparse,nb_scaled=nb_scaled,safe_mode=False)
gp_counts.ConditionalVariance_inducing_points( M = 20) 

Let me know if you need any further help. You can find information about the sparse method in our updated preprint :  https://www.biorxiv.org/content/10.1101/2020.07.29.227207v2

**Comment by ngocphuongtran** [comment]
Thank you for your help! 

Actually I have a different question. I tried to compute the scale factors in R, but it causes an error. That's why I was using the total_counts as scale factors.

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/76912457/107511381-b1b2e800-6ba5-11eb-806b-576adc339891.png">

Can you also help me with this problem?

Thank you in advance.

**Comment by sokratiag** [comment]
Hi, maybe the error is data-set related, I am not sure why there is this error. Make sure that you adapt the .R script to fit the dimensions of your data. If this won't solve the problem, you can either try any other nb regression code to calculate the coefficients or if you still want to use the total counts as scale then you just need to replicate this for each gene so that the dimensions are the correct. I will close the issue but let me know if you have any other questions.

**Comment by sokratiag** [comment]
Hi, I had a look and there is also a negative binomial regression function in python which might be easier to do. Please see the script below to calculate the scales. You can use this one after you loading your Y matrix and X locations (before taking the matrix transpose) and then use  scale = scalesdf as argument in gp_counts = Fit_GPcounts. I tried this way in the mouse dataset and it worked. Soon, I am going to upload an updated notebook with the new code to calculate the scales. I hope this will work for your visium dataset. 

import statsmodels.formula.api as smf 
import statsmodels.api as sm
scales = []
for i in range(0,5):
    model=smf.glm(formula = "Y.iloc[:,i]~0+spatial_locations['total_counts']", data=Y,family=sm.families.NegativeBinomial(sm.families.links.identity())).fit()
    res = model.params[0]*spatial_locations['total_counts']
    scales.append(res)
scalesdf=pd.DataFrame(scales)
scalesdf=scalesdf.T
print(scalesdf)

**Comment by ngocphuongtran** [comment]
Thanks you a lot for your help! 

I will try it.

**Comment by ngocphuongtran** [comment]
I tried to use `gp_counts.ConditionalVariance_inducing_points( M = 20)`, but it causes the following error
<img width="842" alt="image" src="https://user-images.githubusercontent.com/76912457/107757132-6c1d2900-6d25-11eb-8d51-6fd5098cda66.png">

**Comment by sokratiag** [comment]
Hi, this feature has been added only recently so please make sure that you have the latest GPcounts version downloaded on your laptop. There is also a notebook on sparse inference, please see paper_notebooks/scRNA-Seq_time_series for more information on how to implement the sparse version - you need to pass the sparse argument into Fit_GPcounts. It should be something like the following:

gp_counts = Fit_GPcounts(X,Y.loc[genes_name],M = 4, sparse = sparse,safe_mode = True) # use sparse inference

for likelihood in likelihoods:
    results = gp_counts.One_sample_test(likelihood)
    print('The results for '+likelihood+' likelihood:')
    display(results)
    params = gp_counts.load_predict_models(genes_name,test_name,likelihood)
    plot(params,X.values,Y.loc[genes_name],results,sparse)
I am adding @NuhaSaud in case you have any question regarding sparse version as she has implemented that part.

**Comment by teruhironakajima** [comment]
Hi, 
I am trying to reproduce the GPcounts with scRNA-Seq time series demo data but have an error in One_sample_test function.

The errors are as follows:
"TypeError: tf___scalar_log_prob() takes 3 positional arguments but 4 were given"

This is the code.

![2](https://user-images.githubusercontent.com/53326492/196873381-279fce74-4e5f-4825-b454-0a6f3204f8cd.png)

Thank you in advance.

**Comment by teruhironakajima** [comment]
Thank you for your quick response.

The version is as fpllows:
tensorflow==2.10.0
gpflow==2.6.3

Thanks for your help!

**Comment by teruhironakajima** [comment]
I downgraded the gpflow==2.5.2 and it worked well.

Thank you very much.

**Comment by NuhaSaud** [comment]
Yes, unfortunately, the current version of GPcount does not support the last versions of GPflow and tensorflow but we will update it soon.
